version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:dbpassword@db:5432/rails_monitor_development?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
    - db

  redis:
    image: redis

  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "9121:9121"
    depends_on:
    - redis

  web:
    build: .
    command: bash -c "bin/rails db:create && bin/rails db:migrate && bundle exec rails s -b '0.0.0.0'"

    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=dc23501ce6bf6497dd8b01cfbedaa35df7ef885bea64dd205cf2eaf9047beda34ae81337bbdf2b84d3fa74f8300aa8e59bfb220de237aca939c6a8c5401911d6
    depends_on:
      - db
      - redis

  prometheus_exporter:
    build: .
    command: bundle exec prometheus_exporter -b 0.0.0.0 -p 9394
    volumes:
      - ".:/myapp"
    ports:
      - "9394:9394"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  postgres_data:
