global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rails_app'
    static_configs:
      - targets: ['prometheus_exporter:9394']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
