groups:
  - name: rails-app-alerts
    rules:
      - alert: HighHTTP500Errors
        expr: increase(ruby_http_requests_total{status="500"}[1m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High HTTP 500 Error Rate Detected"
          description: "More than 0 HTTP 500 errors in the last 5 minutes."

      - alert: HighRequestDuration
        expr: ruby_http_request_duration_seconds{quantile="0.99"} > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP Request Duration Detected"
          description: "The 99th percentile of HTTP request duration exceeds 0.5 seconds for the last 5 minutes."

  - name: postgresql-alerts
    rules:
      - alert: DatabaseIsDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database is Down"
          description: "The PostgreSQL database is down or not responsive for the last minute."

      - alert: HighActiveConnections
        expr: pg_stat_activity_count{job="postgresql"} > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of active PostgreSQL connections"
          description: "Active connections exceed 80 for more than 5 minutes."

  - name: redis-alerts
    rules:
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes{job="redis"} > 8000000000
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage exceeds 8GB for more than 5 minutes."

      - alert: LowRedisCacheHitRatio
        expr: redis_keyspace_hits{job="redis"} / (redis_keyspace_hits{job="redis"} + redis_keyspace_misses{job="redis"}) < 0.9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low Redis cache hit ratio"
          description: "Cache hit ratio is below 90% for more than 10 minutes."
