{
 "title": "Rails Application Dashboard",
 "tags": [
  "rails",
  "app",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Collector Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collector Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "ruby_collector_rss", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Collector Working Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 1 },
   "targets": [
    { "expr": "ruby_collector_working", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resource Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "description": "Time spent in HTTP requests in seconds. This metric helps in monitoring the performance of the web application by showing how long requests take to complete.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ruby_http_request_duration_seconds_sum / ruby_http_request_duration_seconds_count\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "Total HTTP requests from the web app. This metric helps in understanding the load on the application.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(ruby_http_requests_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Metrics Processed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rate(ruby_collector_metrics_total[5m])\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ruby_collector_sessions_total[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage (RSS) ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "ruby_rss{type=\"web\"}\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Object Allocation Rate Web",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "irate(ruby_allocated_objects_total{type=~\"web\"}[$__rate_interval])\r\n",
       "legendFormat": "{{type}} {{hostname}}"
      }
     ]
    },
    {
     "title": "Major GC Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(ruby_major_gc_ops_total{type=\"web\"}[5m])\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ruby_minor_gc_ops_total{type=\"web\"}[5m])\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Heap Slots (Live and Free)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(ruby_heap_live_slots{type=\"web\"})\r\n",
       "legendFormat": "__auto"
      },
      {
       "expr": "min(ruby_heap_free_slots{type=\"web\"})\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(rate(ruby_http_requests_total[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "http_request_duration_seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(ruby_http_request_duration_seconds_count{action=\"index\",controller=\"welcome\"} [$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}